### PR TITLE
add CHANGELOG.md

### PR DESCRIPTION
**Pull request by jnozsc**
fix https://github.com/ua-parser/uap-python/issues/46

This Changelog was automatically generated by [github_changelog_generator](https://github.com/github-changelog-generator/github-changelog-generator)

### CODE REVIEW

**Comment by mattrobenolt** [comment]
Hmm, I’m not a big fan of this. This doesn’t add any value other than just looking at the commit log. And if anything, this was immediately confusing to me since the top priority things was “Closed Issues” which contained a bunch of stuff that was closed and nothing merged or closed for being invalid. 

Arguably a changelog here would be more reflective of the submodule updates since that’s the real changes.

**Comment by jnozsc** [comment]
`Closed Issues` get removed. 

There are some `uap-core` version bump info from the title of PR, but since this file is automatically generated, the message is from the original commit message.

My opinion is this is better than nothing, and from this first version, people could tweak this by using more accurate commit message in the future or manually fix some details... etc

**Comment by jnozsc** [comment]
@mattrobenolt hi, in https://github.com/ua-parser/uap-python/pull/83/commits/bd994a4c9a06d90922e9c1a8887de20fb2b28039 I add a separate file  for uap-core changelog, lmk any thought

**Comment by mattrobenolt** [comment]
I still really see 0 value in this whatsoever compared to just looking at the commit log and puts more burden on me when I do get around to tagging releases.

**Comment by nolanwilson** [comment]
@mattrobenolt just wanted to leave a note on this as I just came here looking for the release notes for this project. From an outsider's perspective it's helpful because:
1. It provides a single page source where I can go to reference change logs (versus having to scroll through pages of commits / merges).
2. It explicitly lists what changes are included with each version update, versus having to match the release dates with commit dates in Github.
3. It's a document I can link to my colleagues for review when updating this library _(fwiw, this was the reason that I here right now)_

I definitely understand that it's extra overhead for essentially little gain (if not a total net negative) for you as a maintainer, but all of these things are very useful to everyone who uses this package.

A couple of honorable mentions in favor of having a change-log file: 
1. Submodule updates are more difficult to track via the project's commit history and a change-log is a great place to succinctly call these out.
2. A step beyond this at some point would be to list breaking or backwards incompatible changes in your release notes (and/or planned deprecations) as that's the biggest thing I'm looking when I'm working with / updating a package that I use

_And while I've got the floor, thanks for all the work on this package_ 🙌

**Comment by mattrobenolt** [comment]
Here's what I am struggling with here. As a user of this library myself, this changelog gives _me_ no value whatsoever. We aren't changing APIs and hardly any bugs are fixed. It's solely an API wrapper for the submodule.

The changelog provided by the submodule is also not useful since it just links to the git diff between shas, which, frankly GitHub can't even render since some of them are so big.

If anything, what I'd like here is an itemized list of the _actual_ changes from the submodule. I think changes to this repository itself are relatively cosmetic and shouldn't have much importance for you the user. It's more useful to know that like, "Matches for browser X are better." since that's what we're all looking for here.

On a slightly related note, I'm also heavily considering changing versioning here from semver into calver since again, we aren't changing APIs, we just bump a submodule and pray it doesn't have any side effects.

**Comment by mattrobenolt** [comment]
Let's reference the changelog that was produced here.

```
- simplify code and pep8 and apply black formatter [\#80](https://github.com/ua-parser/uap-python/pull/80) ([jnozsc](https://github.com/jnozsc))
- ISSUE-78 Bump uap-core 0.9.10 [\#79](https://github.com/ua-parser/uap-python/pull/79) ([innerverse](https://github.com/innerverse))
- added py37 and py38 to tox. [\#77](https://github.com/ua-parser/uap-python/pull/77) ([j1fig](https://github.com/j1fig))
- Update from uap-core 0.6.7 to 0.6.9 [\#74](https://github.com/ua-parser/uap-python/pull/74) ([dgoldstein0](https://github.com/dgoldstein0))
- update uap-core submodule [\#70](https://github.com/ua-parser/uap-python/pull/70) ([admitad-github](https://github.com/admitad-github))
- Fix license field [\#69](https://github.com/ua-parser/uap-python/pull/69) ([ghost](https://github.com/ghost))
- Add license file to manifest [\#58](https://github.com/ua-parser/uap-python/pull/58) ([bachp](https://github.com/bachp))
```

As a user, 0 of this is useful for you. All of this is internal reworkings, code formatting, license stuff, and expanded testing in CI. 0 API changes or any actual functional changes to consider. If anything, as a user I feel this is more cumbersome and confusing since now I need to read everything to determine if anything is relevant.

**Comment by mattrobenolt** [comment]
And this is the linked to diff for the submodule change: https://github.com/ua-parser/uap-core/compare/fc570f378e41063bad3bdf0532967743efc75b4b...9db18c34f47ee8a30fcd1615ffcbb3ba4e02f287

If anything, these are useful, but it'd be nice if we could pull the actual changes from here instead.

**Comment by mattrobenolt** [comment]
@nolanwilson I'd like to be more open here, so since you landed here looking for a changelog, what were you expecting to find? Is the proposed option here sufficient for you? Would it be sufficient if we say "Just look here at uap-core?" Or would switching to calver be more clear that "we don't change the APIs." I think the issue is that semver implies we might be changing stuff. But really we're just rolling forward with time.

**Comment by nolanwilson** [comment]
@mattrobenolt thanks so much for the background, that all makes a lot of sense to me.

I think calver would honestly clear up a lot of the problems here. Instead of implicit `minor` and `patch` version updates corresponding to changes and fixes respectively, I think calver would make it more clear that this is just being updated to keep in step with the submodule 👍 

And it sounds like the root of a related issue here is a "usable" change-log from the submodule. In reading through some of the diffs, the change-log reads more like the intended audience is maintainers and not package users. But at the end of day, if someone really wants to find this change-log, I think a simple note in the projects README will clear up a lot of confusion here as well. I've included a quick pass at this [here](https://github.com/ua-parser/uap-python/pull/85) to satiate any curious parties. Just going off of my experience, this (in addition to calver) would have provided me with what I was looking for.

**Comment by mattrobenolt** [comment]
Yeah, so what you added over there makes much more sense. The original core of the issue (https://github.com/ua-parser/uap-python/issues/46) was just a misunderstanding. Not someone really needing a changelog since nothing changed. But I agree with clarifying expectations around what this library is responsible for and deflecting to uap-core.

**Pull request closed without merging**
