### PR TITLE
Switch from yaml.load to yaml.safe_load for security

### PR DESCRIPTION
**Pull request by kevinlondon**
`yaml.load` is unfortunately the dangerous version. `yaml.safe_load` has better protections. I had originally opened a [Pull Request with Sentry](https://github.com/getsentry/sentry/pull/1986) that does the same swap. I included a few additional links on that ticket that may be of interest.

Thanks!

### CODE REVIEW

**Comment by elsigh** [comment]
Looks like there are conflicts. Can you rebase? Also can you describe what the danger is here for the record?

**Comment by elsigh** [comment]
Sorry accidental close.

**Comment by kevinlondon** [comment]
No problems about the accidental close! I've made the changes to resolve the merge conflict - not actually sure how that came about. Maybe something was merged recently that changed the syntax. All good now though!

Re: why it's dangerous. I'm working through some popular open source Python projects and looking for potential security vulnerabilities with [Bandit](). Here's the partial output from when I checked this project:

```
Test results:

>> Issue: Use of unsafe yaml load. Allows instantiation of arbitrary objects. Consider yaml.safe_load().
   Severity: Medium   Confidence: High
   Location: ./setup.py:23
22	    json_dest = yaml_dest.replace('.yaml', '.json')
23	    regexes = yaml.load(open(yaml_dest))
24	    with open(json_dest, "w") as f:

>> Issue: Use of unsafe yaml load. Allows instantiation of arbitrary objects. Consider yaml.safe_load().
   Severity: Medium   Confidence: High
   Location: ./ua_parser/user_agent_parser.py:446
445	    yamlFile = open(UA_PARSER_YAML)
446	    regexes = yaml.load(yamlFile)
447	    yamlFile.close()

>> Issue: Use of unsafe yaml load. Allows instantiation of arbitrary objects. Consider yaml.safe_load().
   Severity: Medium   Confidence: High
   Location: ./ua_parser/user_agent_parser.py:461
460	        with open(yamlPath) as fp:
461	            regexes = yaml.load(fp)
462
```

As the warning mentions, `yaml.load()` is unfortunately the unsafe version. I did a [blog post](http://kevinlondon.com/2015/08/15/dangerous-python-functions-pt2.html) on the security risks for yaml's load function, as did [Ned Batchelder](http://nedbatchelder.com/blog/201302/war_is_peace.html) and [others](http://blog.codeclimate.com/blog/2013/01/10/rails-remote-code-execution-vulnerability-explained/).

**Comment by elsigh** [comment]
Cool, thanks for the explanation.

**Pull request merged**
