### PR TITLE
Trove tags

### PR DESCRIPTION
**Pull request by public**
https://github.com/tobie/ua-parser/pull/499

3.2 support would require some workaround for the unicode literals that are used, perhaps by adding six as a dependency.

This will make ua-parser show up as supporting Py3 on sites like http://py3readiness.org/ and in tools like https://github.com/brettcannon/caniusepython3

### CODE REVIEW

**Comment by hwkns** [comment]
:+1:

**Comment by public** [comment]
Merge plz? :)

**Comment by eisensheng** [comment]
:+1: Merge please.

**Comment by public** [comment]
Plz?

**Comment by public** [comment]
:star2: :heart: :+1: plz?

**Comment by elsigh** [comment]
lol, sorry that took an @ mention

**Pull request merged**
