### PR TITLE
Tidy up a couple of things for compliance reasons.

### LINKED ISSUE #150: `LICENSE` is in a subdirectory
The lawyer🐈s have advised me to try to tidy up a couple of things for compliance reasons:

* remove the `LICENSE` file from the `ua_parser` subdirectory;
* add a `LICENSE` file with the canonical [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0.txt) text to the root directory; and
* remove the _Copyright_ section from `README.rst`.

`LICENSE` was moved to `ua_parser/LICENSE` back in June 2012 ostensibly for packaging reasons. Some brief tinkering leads me to believe that `setuptools` handles `license_files=['../LICENSE']` incorrectly, but that a symbolic link would work. Addressing the second point should enable GitHub (and related systems) to detect the licence automatically, which is why this conversation arose.

### PR DESCRIPTION
**Pull request by junyer**
Fixes #150.

### CODE REVIEW

**Comment by junyer** [comment]
(Ping, @renaudd.)

**Comment by masklinn** [comment]
Compliance with what exactly? The PR doesn't say, the linked issue makes assertions but their source is not entirely clear.

And these motivations / justifications should be recorded in the commit message.

The [repository addition process of github](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) seems to agree with the change,

**Comment by masklinn** [comment]
@junyer looks like there were a few bits of CI which were broken, I went and fixed it (hopefully) however it doesn't seem like you enabled "allow edits from maintainers" so I fear you'll have to rebase on your side for CI to pass.

**Comment by junyer** [comment]
Done. Although I accidentally clicked to merge instead of rebase. \*headdesk*

**Comment by masklinn** [comment]
> Done. Although I accidentally clicked to merge instead of rebase. *headdesk*

That's fine, I can just squash at the end.

**Comment by masklinn** [comment]
Thanks.

**Pull request merged**
